### ISSUE TITLE
Steps of the Same Name are Not Printed in the Results

### ISSUE THREAD

**Issue by Streeter8** [webdriverio/wdio-spec-reporter#11] opened 2016-09-15 22:19 UTC
## The Problem

I have a scenario with multiple steps. This scenario will use one of the steps multiple times during it's execution. When the results are printed, only the first occurrence of the step is printed. But it prints with the result of the last occurrence.
## Environment
- WebdriverIO version: `4.2.15`
- Node.js version: `6.5.0`
- wdio testrunner, synchronous
- Additional wdio packages used (if applicable):
  - Cucumber `1.2.2`
  - wdio-cucumber-framework `0.2.5`
  - wdio-spec-reporter `0.0.3`
- Mac OSX 10.11.6
## Code To Reproduce Issue [ Good To Have ]

``` Cucumber
# myFeature.feature
Feature: My Feature

    Scenario: I want to Test the Thing

        Given I navigate to my page
        When  I click on my button
        Then  I should see the picture
        When  I click on my button
        Then  I should not see the picture
```

The resulting printout from the spec reporter will look like this when everything passes

``` bash
------------------------------------------------------------------
[chrome #0a] Session ID: dfc28c3f-592a-46f1-ad1b-90d73a28f76b
[chrome #0a] Spec: /Users/user/project/myFeature.feature
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   My Feature
[chrome #0a]
[chrome #0a]     I want to Test the Thing
[chrome #0a]         ✓ I navigate to my page
[chrome #0a]         ✓ I click on my button
[chrome #0a]         ✓ I should see the picture
[chrome #0a]         ✓ I should not see the picture

5 passing (8s)
```

Or perhaps worse, like this when the _second_ click fails

``` bash
------------------------------------------------------------------
[chrome #0a] Session ID: dfc28c3f-592a-46f1-ad1b-90d73a28f76b
[chrome #0a] Spec: /Users/user/project/myFeature.feature
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   My Feature
[chrome #0a]
[chrome #0a]     I want to Test the Thing
[chrome #0a]         ✓ I navigate to my page
[chrome #0a]         1) I click on my button
[chrome #0a]         ✓ I should see the picture
[chrome #0a]         - I should not see the picture

3 passing (8s)
1 pending
1 failing

1)  I click on my button
The button was not there
running chrome
Error: [Stack Trace]
```
### I expect the following results

When everything passes

``` bash
------------------------------------------------------------------
[chrome #0a] Session ID: dfc28c3f-592a-46f1-ad1b-90d73a28f76b
[chrome #0a] Spec: /Users/user/project/myFeature.feature
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   My Feature
[chrome #0a]
[chrome #0a]     I want to Test the Thing
[chrome #0a]         ✓ I navigate to my page
[chrome #0a]         ✓ I click on my button
[chrome #0a]         ✓ I should see the picture
[chrome #0a]         ✓ I click on my button
[chrome #0a]         ✓ I should not see the picture

5 passing (8s)
```

When the _second_ click fails

``` bash
------------------------------------------------------------------
[chrome #0a] Session ID: dfc28c3f-592a-46f1-ad1b-90d73a28f76b
[chrome #0a] Spec: /Users/user/project/myFeature.feature
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   My Feature
[chrome #0a]
[chrome #0a]     I want to Test the Thing
[chrome #0a]         ✓ I navigate to my page
[chrome #0a]         ✓ I click on my button
[chrome #0a]         ✓ I should see the picture
[chrome #0a]         1) I click on my button
[chrome #0a]         - I should not see the picture

3 passing (8s)
1 pending
1 failing

1)  I click on my button
The button was not there
running chrome
Error: [Stack Trace]
```

**Comment by si-mikey** [comment] 2016-10-31 21:03
So I did some investigation into this issue as I am experiencing it as well. 
The bug seems to be that in webdriverio ( we md5 hash the specs ) 
https://github.com/webdriverio/webdriverio/blob/2548e5737306ab3dc79bc020a30d799b89e38d9d/lib/utils/ReporterStats.js#L134
which is used 
https://github.com/webdriverio/wdio-spec-reporter/blob/master/lib/reporter.js#L246
the problem is that the hash(md5) ( which is going to be the same for steps which are the same ) is inserted into an object as keys and since we can not have the same keys in an object we get specs which are lost.  My solution would be to append a salt to the hash(md5) in this repo so that we don't have duplicate object keys for the specs

**Comment by si-mikey** [comment] 2016-11-04 20:06
@christian-bromann as per my comment above, it seems we might want to add a tid or test_id to the tests and use that as the key for the object or append a tid to the runner.title + tid for the tests so that they are unique in the object. Where does runner.title get set to the test step name?

**Comment by christian-bromann** [comment] 2016-11-04 20:08
> Where does runner.title get set to the test step name?

In the framework adapter.

**Comment by wvankuipers** [comment] 2016-11-18 12:54
The 5 PR's above should resolve this issue. I can image it will take some time to approve them all, but when it's done it will correct the rendering of the report.

**Comment by wvankuipers** [comment] 2016-12-09 07:27
It's finished 😎 

I created a test set-up [here](https://github.com/wvankuipers/wdio-reporter-test) and you can view the outcome [here](https://travis-ci.org/wvankuipers/wdio-reporter-test/builds/182512446).

**Comment by christian-bromann** [comment] 2016-12-09 08:48
Great job @wvankuipers 
This will be fixed with the next release

**Closed by christian-bromann** 2016-12-09 08:48 UTC
Labels: bug, help wanted

**Comment by Streeter8** [comment] 2016-12-09 12:57
Thank you @wvankuipers + @christian-bromann! This is going to help us a lot!

**Comment by scottfalkingham** [comment] 2016-12-13 18:01
It appears this issue is fixed.  However, the spec reporter now outputs the uid along with the messages.

**Comment by wvankuipers** [comment] 2016-12-13 19:19
@scottfalkingham That is strange, what testing framework do you use? (Cucumber, Jasmin or Mocha)

**Comment by scottfalkingham** [comment] 2016-12-13 19:20
Mocha.

**Comment by wvankuipers** [comment] 2016-12-13 19:22
Thanks, I'll get into this

**Comment by wvankuipers** [comment] 2016-12-13 20:16
@christian-bromann Are all versions of the packages affected by this PR already released?

@scottfalkingham Could you please make sure you are using the latest versions of Webdriverio, wdio-spec-reporter and wdio-mocha-framework?

I can't reproduce this issue with the latest version of these packages, the only issue I can find is the UID being displayed in the suite name, and I'm creating a fix for that asap.

    > wdio-test@0.1.0 test:mocha /Users/w.vankuipers/Sites/wdio-test
    > wdio mocha/wdio.conf.js

    ------------------------------------------------------------------
    [phantomjs #0-0] Session ID: 8b480dd0-c16d-11e6-85e0-e554bdb661b0
    [phantomjs #0-0] Spec: /Users/w.vankuipers/Sites/wdio-test/mocha/test.js
    [phantomjs #0-0] Running: phantomjs
    [phantomjs #0-0]
    [phantomjs #0-0]   My Feature1
    [phantomjs #0-0]
    [phantomjs #0-0]   My Feature
    [phantomjs #0-0]       ✓ should go to the home page
    [phantomjs #0-0]       ✓ should go to the API page
    [phantomjs #0-0]       ✓ should go to the home page
    [phantomjs #0-0]
    [phantomjs #0-0]
    [phantomjs #0-0] 3 passing (7s)
    [phantomjs #0-0]

I use this repo as a test reference https://github.com/wvankuipers/wdio-reporter-test

**Comment by scottfalkingham** [comment] 2016-12-13 21:00
I'm using webdriver 4.5.0, wdio-spec-reporter 0.0.3 and wdio-mocha-framework 0.5.6.  Removed node_modules and reinstalled.  Same result.

Also, I can confirm that your test repo does not reproduce the issue using the mocha test.

**Comment by wvankuipers** [comment] 2016-12-13 21:08
@scottfalkingham Thanks for the info, it seams the wdio-spec-reporter changes where not yet released. Could you try the new released version (0.0.4) and let me know the results? Thanks in advance

**Comment by scottfalkingham** [comment] 2016-12-14 16:07
@wvankuipers It is improved.  The main output no longer has the numbers appended to it, however there is still a number appended to the first output.

```[phantomjs #0-0] Session ID: b41ef1e5-5da1-4932-98e3-130b57bb239f
[phantomjs #0-0] Spec: c:\path\test.js
[phantomjs #0-0] Running: phantomjs
[phantomjs #0-0]
[phantomjs #0-0]   Test1
[phantomjs #0-0]
[phantomjs #0-0]   Test
[phantomjs #0-0]       √ should do something
[phantomjs #0-0]
[phantomjs #0-0]
[phantomjs #0-0] 1 passing (14s)
[phantomjs #0-0]```

**Comment by wvankuipers** [comment] 2016-12-15 06:55
Yes that was the issue I was describing here:

> I can't reproduce this issue with the latest version of these packages, the only issue I can find is the UID being displayed in the suite name, and I'm creating a fix for that asap.

Already working on a fix

**Comment by wvankuipers** [comment] 2016-12-16 12:39
Fixed with https://github.com/webdriverio/wdio-spec-reporter/pull/15 and https://github.com/webdriverio/webdriverio/pull/1767

Should be in the next release of WebdriverIO.
